# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:36:49+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class ActivityLevel(Enum):
    ACTIVITY_LEVEL_UNSPECIFIED = 'ACTIVITY_LEVEL_UNSPECIFIED'
    UNEVALUATED = 'UNEVALUATED'
    UNUSUAL = 'UNUSUAL'
    UNKNOWN = 'UNKNOWN'
    TYPICAL_BASIC = 'TYPICAL_BASIC'
    TYPICAL_STRONG = 'TYPICAL_STRONG'


class AccountActivity(BaseModel):
    activityLevel: Optional[ActivityLevel] = Field(
        None, description='Required. Indicates the activity level of the account.'
    )


class AppLicensingVerdict(Enum):
    UNKNOWN = 'UNKNOWN'
    LICENSED = 'LICENSED'
    UNLICENSED = 'UNLICENSED'
    UNEVALUATED = 'UNEVALUATED'


class AccountDetails(BaseModel):
    accountActivity: Optional[AccountActivity] = Field(
        None,
        description='Details about the account activity for the user in the scope.',
    )
    appLicensingVerdict: Optional[AppLicensingVerdict] = Field(
        None,
        description='Required. Details about the licensing status of the user for the app in the scope.',
    )


class AppRecognitionVerdict(Enum):
    UNKNOWN = 'UNKNOWN'
    PLAY_RECOGNIZED = 'PLAY_RECOGNIZED'
    UNRECOGNIZED_VERSION = 'UNRECOGNIZED_VERSION'
    UNEVALUATED = 'UNEVALUATED'


class AppIntegrity(BaseModel):
    appRecognitionVerdict: Optional[AppRecognitionVerdict] = Field(
        None, description='Required. Details about the app recognition verdict'
    )
    certificateSha256Digest: Optional[List[str]] = Field(
        None,
        description="The SHA256 hash of the requesting app's signing certificates (base64 web-safe encoded). Set iff app_recognition_verdict != UNEVALUATED.",
    )
    packageName: Optional[str] = Field(
        None,
        description='Package name of the application under attestation. Set iff app_recognition_verdict != UNEVALUATED.',
    )
    versionCode: Optional[str] = Field(
        None,
        description='Version code of the application. Set iff app_recognition_verdict != UNEVALUATED.',
    )


class DecodeIntegrityTokenRequest(BaseModel):
    integrityToken: Optional[str] = Field(None, description='Encoded integrity token.')


class DeviceRecognitionVerdictEnum(Enum):
    UNKNOWN = 'UNKNOWN'
    MEETS_BASIC_INTEGRITY = 'MEETS_BASIC_INTEGRITY'
    MEETS_DEVICE_INTEGRITY = 'MEETS_DEVICE_INTEGRITY'
    MEETS_STRONG_INTEGRITY = 'MEETS_STRONG_INTEGRITY'
    MEETS_VIRTUAL_INTEGRITY = 'MEETS_VIRTUAL_INTEGRITY'


class DeviceIntegrity(BaseModel):
    deviceRecognitionVerdict: Optional[List[DeviceRecognitionVerdictEnum]] = Field(
        None,
        description='Details about the integrity of the device the app is running on',
    )


class RequestDetails(BaseModel):
    nonce: Optional[str] = Field(
        None,
        description='Nonce that was provided in the request (which is base64 web-safe no-wrap).',
    )
    requestHash: Optional[str] = Field(
        None, description='Request hash that was provided in the request.'
    )
    requestPackageName: Optional[str] = Field(
        None,
        description='Required. Application package name this attestation was requested for. Note: This field makes no guarantees or promises on the caller integrity. For details on application integrity, check application_integrity.',
    )
    timestampMillis: Optional[str] = Field(
        None,
        description='Required. Timestamp, in milliseconds, of the integrity application request.',
    )


class TestingDetails(BaseModel):
    isTestingResponse: Optional[bool] = Field(
        None,
        description='Required. Indicates that the information contained in this payload is a testing response that is statically overridden for a tester.',
    )


class TokenPayloadExternal(BaseModel):
    accountDetails: Optional[AccountDetails] = Field(
        None, description='Required. Details about the Play Store account.'
    )
    appIntegrity: Optional[AppIntegrity] = Field(
        None, description='Required. Details about the application integrity.'
    )
    deviceIntegrity: Optional[DeviceIntegrity] = Field(
        None, description='Required. Details about the device integrity.'
    )
    requestDetails: Optional[RequestDetails] = Field(
        None, description='Required. Details about the integrity request.'
    )
    testingDetails: Optional[TestingDetails] = Field(
        None,
        description='Indicates that this payload is generated for testing purposes and contains any additional data that is linked with testing status.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class DecodeIntegrityTokenResponse(BaseModel):
    tokenPayloadExternal: Optional[TokenPayloadExternal] = Field(
        None,
        description='Plain token payload generated from the decoded integrity token.',
    )
